from google import genai
from google.adk.models import Gemini
from google.genai import types


from .. import config

client = genai.Client(api_key=config.GEMINI_API_KEY, vertexai=False)

async def youtube_summary(url: str, query: str):
    """
    Answer questions about a specific YouTube video, focusing on specific query
    
    Args:
        url (str): a YouTube URL
        query (str): a query or questions to answer about the video
    """
    model = config.GOOGLE_FLASH_MODEL.model if isinstance(config.GOOGLE_FLASH_MODEL, Gemini) else config.GOOGLE_FLASH_MODEL

    try:
        response = client.models.generate_content(
            model=model,
            contents=[
                types.Part(
                    file_data=types.FileData(file_uri=url, mime_type="video/mp4"),
                ),
                types.Part(text=query),
            ],
        )
        response_text = ''
        if response and response.candidates and response.candidates[0] and response.candidates[0].content and response.candidates[0].content.parts:
            parts = response.candidates[0].content.parts
            for part in parts:
                if part.text:
                    response_text += part.text
            return {"status":"success","message":response_text}
        else:
            return {"status":"failed", "message":"No response was generated by the model"}
    except Exception as e:
        return {"status":"error", "message":e}